### ISSUE TITLE
 permission denied for this window type

### ISSUE THREAD

**Issue by vidjanidhi** [Mirrorhanyu/AssistiveTouch#1]
I have an issue during implementing your service... 
It displays an error like bleow:

java.lang.RuntimeException: Unable to create service 
.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@bc3a4e -- permission denied for this window type
                      at android.app.ActivityThread.handleCreateService(ActivityThread.java:3035)
                      at android.app.ActivityThread.access$1900(ActivityThread.java:150)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1495)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:168)
                      at android.app.ActivityThread.main(ActivityThread.java:5885)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
                   Caused by: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@bc3a4e -- permission denied for this window type
                      at android.view.ViewRootImpl.setView(ViewRootImpl.java:629)
                      at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:310)
                      at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
                      at com.astouch.cb.assistivetouch.AssistiveTouchService.createAssistiveTouchView(AssistiveTouchService.java:106)
                      at com.astouch.cb.assistivetouch.AssistiveTouchService.onCreate(AssistiveTouchService.java:62)
                      at android.app.ActivityThread.handleCreateService(ActivityThread.java:3017)
                      at android.app.ActivityThread.access$1900(ActivityThread.java:150) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1495) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:168) 
                      at android.app.ActivityThread.main(ActivityThread.java:5885) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)

**Comment by soumithganji** [comment]
hi!
could ypu fix the problem faced in the app?

**Comment by mirrorhanyu** [comment]
Hi,

Thanks for your interest in this application, but it is no longer maintained, and the code of this implementation is not the best practice to fit the latest android development. my suggestion would be implement this kind of feature by your own new way.
